[package]
name = "gas-predictor"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.17", features = ["ndarray", "autodiff"] }

[[bin]]
name = "train"
path = "src/main.rs"

[[bin]]
name = "infer"
path = "src/inference.rs"