[package]
name = "gas-predictor"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = "0.17"
burn-ndarray = "0.17"

[[bin]]
name = "train"
path = "src/main.rs"

[[bin]]
name = "infer"
path = "src/inference.rs"